// Options the user could type in
const prompts = [
  ["lorenzo"],
  [""]
]

// Possible responses, in corresponding order

const replies = [
  ["that's my name", "get a life"],
  ["*shifts uncomfortably* uhhhhhh *silence crescendos*"]
]

// Random for any other user input

const alternative = [
  "L BOZO + RATIO", "Bro really would do that","Cope","Cope, cope, cope","Based","Bro got caught in HIGH resolution","Man got caught in 4K","You would do that","I'ma go demon time","L bozo","Bro","Bruh","Go crazy","Man went CRAZY","Bro went CRAZY","Big dubs were taken","Ez","Trippin","Man's trippin","Naaaah bro","That's incorrect","Yeah, its big brain time","small brain moment","Average human moment","Average [insert your favorite activity here] enjoyer","*laughs* You would say that *laughing intensifies*","Yeah, but have I told you that I went to nationals in sailing, bro?","Bruh moment","Bro moment","Rip bozo","Rip","Facts","True facts","Me personally; would not do that","Me personally; would'n't take that","Ima be clowning on you","Clown","On God","lol get rekt","Bros literally an NPC"
]

// Whatever else

const coronavirus = ["The King of France was Absolute, the people all were destitute, the year was 17 and 89. Churches paid no income tax, neither did aristocrats and wars were costing money all the time. But Enlightenment Ideas, had entered people’s ears like Liberty, Equality and Brotherhood. People starved and broke under feudalism's yoke knew no church or king was gonna do them any good. There was such financial crisis, the king had to take advice, to try an old thing called Estates General government. The estates general had 3 votes, Nobles, Church and Common Folks, 2 to 1 the commons lose it always went. The commons in frustration said we represent the nation, the nobles and the church must lose their privileges. And the rich were scared for real when they stormed to the Bastille and rebellions also broke out in the villages. At the palace in Versailles, the king and queen were heard to sigh when the national assembly made a bill of rights. Then the Women's march embarrassed them and chased them into Paris and the church and nobles lost their power overnight. Arguments got hot whether to keep the King or not, different groups saw different ways to run the country best. But when the Royal family tried to flee the country in disguise, they were busted and then put under a house arrest. All of Europe's Kings were terrified to hear these things, so France was threatened on all sides by enemies. And when these other kings declared the King of France had to spared, this made the King of France look worse to the Revolutionaries. They had built a new machine the quick and painless guillotine, they said it's fairer than the King's Medieval Torture rack. Then they put it on a vote and then dropped it on his throat and every king across the world just had a heart attack. They attacked from North and South, and they attacked from East and West, Revolutionary France was in a desperate state. And when the radical Marat was killed politically that was what it took for France's outlook to degenerate. The new leader Robespierre said enemies were everywhere, and for a year the Guillotine was working endlessly. And though he freed the slaves that’s true Robespierre’s head came off too and France was run by the more moderate directory. But the directory was lame and France's only good news came from their armies now in Europe winning more and more. And the man who made them win was General Napoleon and when he came back home he made himself the emperor. So it was a painful climb to get from Kings to Modern times, but the French Revolution always paved the way. 'Cause the ideas that sparked the first, have never ever been reversed, it was biggest change that shaped our western world today"]
const sailing = ["There once was a ship that put to sea The name of the ship was the Billy of Tea The winds blew up, her bow dipped down Oh blow, my bully boys, blow (huh) Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go She'd not been two weeks from shore When down on her a right whale bore The captain called all hands and swore He'd take that whale in tow (huh) Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go Da-da-da-da-da Da-da-da-da-da-da-da Da-da-da-da-da-da-da-da-da-da-da Before the boat had hit the water The whale's tail came up and caught her All hands to the side, harpooned and fought her When she dived down low (huh) Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go No line was cut, no whale was freed The captain's mind was not of greed And he belonged to the Whaleman's creed She took that ship in tow (huh) Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go Da-da-da-da-da Da-da-da-da-da-da-da Da-da-da-da-da-da-da-da-da-da-da For forty days or even more The line went slack then tight once more All boats were lost, there were only four But still that whale did go (huh) Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go As far as I've heard, the fight's still on The line's not cut, and the whale's not gone The Wellerman makes his regular call To encourage the captain, crew and all (huh) Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go Soon may the Wellerman come To bring us sugar and tea and rum One day, when the tonguing is done We'll take our leave and go "]
